language: php

php:
  - 7.0

before_script:
  - cp .env.travis .env
  - composer config --global github-oauth.github.com $GITHUBPAK
  - composer self-update
  - composer install -n
  - php artisan key:generate
  - php artisan config:clear
  - php artisan migrate:refresh --seed
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - ./vendor/laravel/dusk/bin/chromedriver-linux &
  - php artisan serve > /dev/null 2>&1 &

script:
  - vendor/bin/phpunit
  - php artisan dusk

cache:
  directories:
    - node_modules
    - vendor