name: Laravel

on:
  push:
    branches: [ main, staging ]
  pull_request:


concurrency: production_environment

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: /tmp/composer-cache
          key: "${{ runner.os }}-${{ hashFiles('**/composer.lock') }}"
      - uses: php-actions/composer@v6

      - name: Generate key
        run: php artisan key:generate
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Create Database
        run: |
          mkdir -p database
          touch database/database.sqlite
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: vendor/bin/pest

  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    name: Deploy Scarlet to London
    needs: tests
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name: Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:scarlet
      - name: Deploy to Staging
        if: github.ref == 'refs/heads/staging'
        uses: deployphp/action@v1
        with:
          private-key: ${{ secrets.SSH_KEY }}
          dep: deploy staging
      - name: Deploy to Production
        if: github.ref == 'refs/heads/main'
        uses: deployphp/action@v1
        with:
          private-key: ${{ secrets.SSH_KEY }}
          dep: deploy production
